<?php
if (!isset($GLOBALS['hashIdentificaIndexAtan']) || $GLOBALS['hashIdentificaIndexAtan'] != md5($GLOBALS['chave_md5'])) {
    die("Acesso negado");
}
?>
<!doctype html>
<html class="no-js" lang="pt"> 
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <title><?php echo "Atan"; //echo $sys_config['titulo'] . ' - ' . $reg_nome;  ?></title>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width" />
        <link rel="stylesheet" type="text/css" href="<?php echo $caminho_pasta_web_files; ?>/css/reset.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $caminho_pasta_web_files; ?>/css/main.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $caminho_pasta_web_files; ?>/css/grid.css" />
        <link rel="stylesheet" type="text/css" href="<?php echo $caminho_pasta_web_files; ?>/css/responsive.css" />
        <script type="text/javascript" src="<?php echo $caminho_pasta_web_files; ?>/js/jquery.min.js"></script>
        <title>Login</title>
    </head>
    <body>
        <div class="container_24">
            <div class="push_8 grid_8 logo">
                <img src="<?php echo $caminho_pasta_web_files; ?>/img/logo_ata.png" style="width: 80%; height: 80%;"/>
            </div>
        </div>
        <section id="login" class="container_24">
            <div class="well push_8 grid_8">
                <?php
                if (isset($view) && !empty($view)) {
                    $this->getView($view);
                }
                ?>
            </div>       
        </section>
        <script>window.jQuery || document.write('<script src="<?php echo $caminho_pasta_web_files; ?>/js/libs/jquery-1.7.1.min.js"><\/script>')</script>
        <script type="text/javascript" src="<?php echo $caminho_pasta_web_files; ?>/js/bootstrap.js"></script>
        <script src="<?php echo $caminho_pasta_web_files; ?>/js/plugins.js"></script>
        <script src="<?php echo $caminho_pasta_web_files; ?>/js/script_login.js"></script>
    </body>
</html>