<?php

if (!isset($GLOBALS['hashIdentificaIndexAtan']) || $GLOBALS['hashIdentificaIndexAtan'] != md5($GLOBALS['chave_md5']))
{
    die("Acesso negado");
}

?>
<html>
    <head>
        <title>Logar</title>
    </head>
    
    <body>
        <form action="logado" method="post">
            Login: <input type="text" name="login"><br>
            Senha: <input type="password" name="senha">
            <input type="submit" value="enviar">
        </form> 
    </body>
</html>