<?php

if (!isset($GLOBALS['hashIdentificaIndexAtan']) || $GLOBALS['hashIdentificaIndexAtan'] != md5($GLOBALS['chave_md5']))
{
    die("Acesso negado");
}

?>
<html>
    <head>
        <title>Logando</title>
    </head>
    
    <body>
        <p>Parabens, voce esta logado com o usuario <strong><?=$view_login?></strong> e com a senha <strong><?=$view_senha?></strong></p>
        <a href="index">Ir para index</a>
    </body>
</html>